version: '3.7'

services:
  backend:
    volumes:
      - ./backend:/app
    build:
      context: .
      dockerfile: ./Dockerfile.backend
    environment: &default_environment
      PAGER: less
      LESSCHARSET: 'UTF-8'
    command: bash -c "rm -f tmp/pids/server.pid && bin/update && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true

  frontend:
    volumes:
      - ./frontend:/app
    build:
      context: .
      dockerfile: ./Dockerfile.frontend
    environment:
      <<: *default_environment
    command: bash -c "npm start"
    ports:
      - '4100:4100'
    stdin_open: true
    tty: true
